FROM node:14-alpine
RUN apk add --no-cache \
        chromium

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

EXPOSE 3000/tcp
WORKDIR /app
COPY ./package.json /app
COPY ./yarn.lock /app
RUN yarn install
COPY . /app

ARG BASE_URL=/
ENV BASE_URL=$BASE_URL

RUN yarn build
ENTRYPOINT ["node", "/app/server/index.js"]
